//
//  MeteoModels.swift
//  Meteo App
//
//  Created by Yakoubi Mohammed on 25/8/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Meteo : Codable
{
  // MARK: Use cases
    let id : Int?
    let name : String?
    let coord : Coord?
    let weather : [Weather]?
    let base : String?
    let main : Main? 
    let timezone : Int?
    let cod : Int?
}
struct Coord: Codable
{
    let lon : Double?
    let lat : Double?
}
struct Weather: Codable
{
    let id : Int?
    let main : String?
    let description: String?
}

struct Main: Codable
{
    let temp : Double?
    let feels_like : Double?
    let temp_min: Double?
    let temp_max : Double?
    let pressure : Double?
    let humidity: Int?
}
