//
//  MeteoWorker.swift
//  Meteo App
//
//  Created by Yakoubi Mohammed on 25/8/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import Promises
class MeteoWorker
{
    func getData(localName: String) -> Promise<Meteo> {
        return MeteoAPIClient.getMeteo(localName: localName) 
    }
}
