//
//  welcomePresenter.swift
//  Meteo App
//
//  Created by Yakoubi Mohammed on 25/8/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol welcomePresentationLogic
{
  func presentSomething(response: welcome.Something.Response)
}

class welcomePresenter: welcomePresentationLogic
{
  weak var viewController: welcomeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: welcome.Something.Response)
  {
    let viewModel = welcome.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
